name: Build (C/C++ CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #workflow_call: #  Checking reusable workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -DENABLE_TESTING:BOOL=TRUE -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: export CXXFLAGS="-Werror" && cmake --build .
